name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and run checks
        run: |
          ./gradlew :app:detectStringResourceInNonComposable --no-daemon
          ./gradlew :app:assembleDebug --no-daemon --stacktrace
        env:
          CI: true

      - name: Run unit tests
        run: ./gradlew test --no-daemon
